version: '3'

services:
  camera_processor:
    build: 
      context: ./camera
    ports:
      - "8000:8000"
    devices:
      - "/dev/video1:/dev/video0"
    privileged: true

  viewer:
    build: 
      context: ./mock_viewer
    ports:
      - "8001:8001"
    depends_on:
      - camera_processor

networks:
  default:
    driver: bridge