### DATA PARAMETRS
dataset_type: folders # Описание в документации [folders, yaml] Тип датасета folders, еще бывают yaml
path_data: /home/jovyan/anurov/Leafs/train_set/  # dataset root dir
path_out: /home/jovyan/anurov/Leafs/out_train/

## Params model architecture
backend_model: timm
architecture_model: levit_384.fb_dist_in1k

# classes classifer
classes: [ '1', '2', '3', '4', '5']

# params for dataset
use_albu: True
use_norm: Falses
size: 224 # image size


device: null
num_workers: 12
save_best: 3



### HYPER-PARAMETRS
#hyperparameters:
batch_size: 64
lr: 0.001
epochs: 300


## Tracker Results Reporters
tracker_columns: ['epoch', 'train_loss', 'train_acc', 'valid_loss', 'valid_acc','name_checkpoint', 'lr']


